#!/usr/bin/env python3
"""
Generate HiFloat8 encoding/decoding lookup tables.

This script enumerates all HiFloat8-representable values and generates
C/CUDA header files with constant lookup tables for encoding/decoding.
"""

import sys
import math
from typing import List, Tuple


def enumerate_hif8_values() -> List[float]:
    """Enumerate all distinct positive HiFloat8 representable values."""
    values = set()
    values.add(0.0)

    # Denormal: X = 2^(M-23), M in [1,7]
    for M in range(1, 8):
        values.add(2.0 ** (M - 23))

    # Normal: X = 2^E * (1 + m / 2^mantissa_bits)
    # |E| in {0,1,2,3}: mantissa_bits=3
    # |E| in {4,5,6,7}: mantissa_bits=2
    # |E| in {8..15}:   mantissa_bits=1
    for E in range(-15, 16):
        abs_E = abs(E)
        if abs_E <= 3:
            mb = 3
        elif abs_E <= 7:
            mb = 2
        else:
            mb = 1
        for m in range(2**mb):
            val = (2.0 ** E) * (1.0 + m / (2.0 ** mb))
            # Exclude the Inf encoding: 2^15 * 1.5
            if val >= 1.5 * 2**15:
                continue
            values.add(val)

    return sorted(values)


def float_to_hex_string(f: float) -> str:
    """Convert float to C-style hex float literal."""
    if f == 0.0:
        return "0.0f"
    elif math.isinf(f):
        return "INFINITY" if f > 0 else "-INFINITY"
    elif math.isnan(f):
        return "NAN"
    else:
        # Use hex float format for exact representation
        return f.hex() + "f"


def generate_header(values: List[float]) -> str:
    """Generate C/CUDA header file with LUT."""

    header = """// Auto-generated by scripts/generate_lut.py
// DO NOT EDIT MANUALLY

#ifndef HIFLOAT8_LUT_H
#define HIFLOAT8_LUT_H

#include <stdint.h>

// Number of distinct positive HiFloat8 values (including zero)
#define HIF8_LUT_SIZE {lut_size}

// Decode LUT: index -> float value
// Usage: float val = HIF8_DECODE_LUT[index];
__constant__ const float HIF8_DECODE_LUT[HIF8_LUT_SIZE] = {{
""".format(lut_size=len(values))

    # Format values in rows of 4
    for i in range(0, len(values), 4):
        row_values = values[i:i+4]
        row_hex = [float_to_hex_string(v) for v in row_values]
        if i + 4 < len(values):
            header += "    " + ", ".join(row_hex) + ",\n"
        else:
            header += "    " + ", ".join(row_hex) + "\n"

    header += "};\n\n"

    # Add convenience macros
    header += """// Special index values
#define HIF8_IDX_ZERO 0
#define HIF8_IDX_MAX {max_idx}
#define HIF8_IDX_INF 127

// Encoding helper: binary search to find closest value
// Returns index in [0, HIF8_LUT_SIZE-1]
__device__ __forceinline__ uint8_t hif8_find_index(float magnitude) {{
    // Handle exact zero
    if (magnitude == 0.0f)
        return HIF8_IDX_ZERO;

    // Binary search in sorted LUT
    int left = 0;
    int right = HIF8_LUT_SIZE - 1;

    while (left < right) {{
        int mid = (left + right) / 2;
        if (HIF8_DECODE_LUT[mid] < magnitude) {{
            left = mid + 1;
        }} else {{
            right = mid;
        }}
    }}

    // Check if left-1 is closer
    if (left > 0) {{
        float dist_left = fabsf(HIF8_DECODE_LUT[left] - magnitude);
        float dist_prev = fabsf(HIF8_DECODE_LUT[left - 1] - magnitude);
        if (dist_prev < dist_left) {{
            left = left - 1;
        }}
    }}

    return (uint8_t)left;
}}

// Decoding helper: direct lookup
__device__ __forceinline__ float hif8_lookup_value(uint8_t index) {{
    uint8_t idx = index & 0x7F;  // Mask to 7 bits
    if (idx == HIF8_IDX_INF)
        return __int_as_float(0x7f800000);  // +Inf
    return HIF8_DECODE_LUT[idx];
}}

#endif // HIFLOAT8_LUT_H
""".format(max_idx=len(values)-1)

    return header


def generate_test_vectors(values: List[float]) -> str:
    """Generate Python test vectors for validation."""

    code = '''"""Auto-generated test vectors for HiFloat8 encoding/decoding."""

import math

# All HiFloat8-representable positive values
HIF8_VALUES = [
'''

    # Format values
    for i in range(0, len(values), 4):
        row = values[i:i+4]
        code += "    " + ", ".join(f"{v:.17e}" for v in row) + ",\n"

    code += "]\n\n"

    code += """# Test vectors: (input, expected_rounded, expected_index)
TEST_VECTORS = [
    # Exact values (should encode to themselves)
"""

    # Add some exact value test cases
    test_indices = [0, 1, 10, 50, 100, len(values)-1]
    for idx in test_indices:
        if idx < len(values):
            val = values[idx]
            code += f"    ({val:.17e}, {val:.17e}, {idx}),  # Exact: index {idx}\n"

    code += """
    # Rounding cases (values between representable points)
    (1.3e-6, 1.9073486328125e-06, None),  # Round to denormal
    (1.6e-6, 1.9073486328125e-06, None),  # Round up
    (15.5, 16.0, None),                   # Zone boundary

    # Edge cases
    (2**(-24), 0.0, 0),                   # Underflow to zero
    (50000.0, 32768.0, None),             # Clamp to max
]

# Special value mappings
SPECIAL_ENCODINGS = {
    'zero': 0x00,
    'max': 0x7E,      # index 126 = 32768 (largest finite value)
    'inf': 0x7F,      # index 127 = +Inf
    'neg_zero': 0x80,
    'neg_max': 0xFE,   # index 126 | sign = -32768
    'neg_inf': 0xFF,   # index 127 | sign = -Inf
}
"""

    return code


def main():
    print("Generating HiFloat8 LUT...")

    # Enumerate all values
    values = enumerate_hif8_values()
    print(f"Found {len(values)} distinct positive values")
    print(f"Range: [{min(values):.2e}, {max(values):.2e}]")

    # Verify count fits in 7 bits
    if len(values) > 128:
        print(f"ERROR: Too many values ({len(values)}) for 7-bit encoding!")
        sys.exit(1)

    # Generate header file
    header_path = "../hifloat8_quant/csrc/hifloat8_lut.h"
    header_content = generate_header(values)
    with open(header_path, "w") as f:
        f.write(header_content)
    print(f"✓ Generated {header_path}")

    # Generate test vectors
    test_path = "../test_vectors.py"
    test_content = generate_test_vectors(values)
    with open(test_path, "w") as f:
        f.write(test_content)
    print(f"✓ Generated {test_path}")

    # Print statistics
    print("\nStatistics:")
    print(f"  Total values: {len(values)}")
    print(f"  Bits required: 7 (fits in uint8 with 1 sign bit)")
    print(f"  Denormals: {sum(1 for v in values if v > 0 and v < 2**(-15))}")
    print(f"  Normals: {sum(1 for v in values if v >= 2**(-15))}")
    print(f"  LUT size: {len(values) * 4} bytes (float32)")

    print("\nDone! Next steps:")
    print("  1. Review generated hifloat8_lut.h")
    print("  2. Implement hifloat8_encode_decode.cu using the LUT")
    print("  3. Add Python bindings in hifloat8_quant.cpp")


if __name__ == "__main__":
    main()
