#!/usr/bin/env python3
"""
Generate the float-bits → HiFloat8-byte encode LUT.

The existing encoder runs `hif8_round_float` (ldexp/floor math) followed
by `hif8_find_index` (log2(127)-step binary search) per element. Both can
be folded into a single `__constant__` memory load.

Why 12 bits is enough:
  * HiFloat8 uses round-half-away-from-zero, so no sticky bit is required.
  * The widest mantissa zone keeps 3 bits, plus 1 round bit = 4 mantissa
    bits suffice to determine the rounded value uniquely.
  * Add 8 exponent bits → 12-bit index → 4096 entries × 1 byte = 4 KB.
  * NaN handling needs all 23 mantissa bits to distinguish it from +Inf
    when `exp == 0xFF`, so the kernel branches on that one row.

Outputs `custom_ops/hifloat8_cuda/hifloat8_encode_lut.h` containing two
parallel 4096-entry tables: HIF8_ENCODE_LUT_RANK_LO and
HIF8_ENCODE_ASCEND_LO. Both store the lower 7 bits (sign is OR'd in by
the kernel).

Entries for `exp == 0xFF` are unused at runtime (the kernel branches),
but we store sentinel 0x00 for safety.
"""

from __future__ import annotations

import math
import os
import struct
import sys

import numpy as np
import en_dtypes as en

# Reuse the validated reference round implementation already living next
# to this script's home (verify_hifp8_vs_endtypes.py).
sys.path.insert(0, os.path.join(os.path.dirname(__file__), os.pardir))
from verify_hifp8_vs_endtypes import hif8_round_repo  # noqa: E402


# ---------------------------------------------------------------------------
# Mirror the repo's HIF8_DECODE_LUT (rank → magnitude) so we can invert it.
# ---------------------------------------------------------------------------

def enumerate_repo_lut() -> list[float]:
    values = {0.0}
    for M in range(1, 8):
        values.add(2.0 ** (M - 23))
    for E in range(-15, 16):
        ae = abs(E)
        mb = 3 if ae <= 3 else (2 if ae <= 7 else 1)
        for m in range(2 ** mb):
            v = (2.0 ** E) * (1.0 + m / (2.0 ** mb))
            if v >= 1.5 * 2 ** 15:
                continue
            values.add(v)
    return sorted(values)


def build_magnitude_to_byte():
    """Return two dicts mapping magnitude → (lut_rank_byte, ascend_byte)."""
    repo_lut = enumerate_repo_lut()                # length 127
    mag_to_rank = {v: i for i, v in enumerate(repo_lut)}
    mag_to_rank[math.inf] = 127

    en_bytes = np.arange(256, dtype=np.uint8).view(en.hifloat8).astype(np.float64)
    mag_to_ascend = {}
    for b in range(256):
        v = float(en_bytes[b])
        if math.isnan(v):
            continue
        if math.isinf(v) and v > 0:
            mag_to_ascend[math.inf] = b & 0x7F
            continue
        if math.isinf(v):
            continue
        mag_to_ascend[abs(v)] = b & 0x7F

    # Sanity
    for mag in repo_lut:
        if mag == 0.0:
            assert mag_to_ascend.get(0.0, 0) == 0
        else:
            assert mag in mag_to_ascend, f"missing Ascend code for {mag}"
    return mag_to_rank, mag_to_ascend


# ---------------------------------------------------------------------------
# Build the 4096-entry tables
# ---------------------------------------------------------------------------

def float_from_bits(bits: int) -> float:
    return struct.unpack("<f", struct.pack("<I", bits & 0xFFFFFFFF))[0]


def build_encode_tables():
    mag_to_rank, mag_to_ascend = build_magnitude_to_byte()

    rank_lut = [0] * 4096
    ascend_lut = [0] * 4096

    for exp in range(256):
        for top4 in range(16):
            idx = (exp << 4) | top4

            if exp == 0xFF:
                # Branch handled by kernel; store 0 sentinel.
                rank_lut[idx] = 0
                ascend_lut[idx] = 0
                continue

            # Build a positive float32 with the chosen (exp, top4) and
            # zero lower mantissa bits. Round-half-away-from-zero only
            # needs the round bit (which is included in top4); lower bits
            # don't change the result.
            bits = (exp << 23) | (top4 << 19)
            x = float_from_bits(bits)

            mag = hif8_round_repo(x)               # in [0, +inf]
            assert mag >= 0
            if math.isinf(mag):
                rank_lut[idx] = mag_to_rank[math.inf]
                ascend_lut[idx] = mag_to_ascend[math.inf]
            else:
                rank_lut[idx] = mag_to_rank[mag]
                ascend_lut[idx] = mag_to_ascend[mag]

    return rank_lut, ascend_lut


# ---------------------------------------------------------------------------
# Header emission
# ---------------------------------------------------------------------------

HEADER_TEMPLATE = """\
// Auto-generated by scripts/generate_encode_lut.py
// DO NOT EDIT MANUALLY
//
// Float32 → HiFloat8 byte encode tables.
//
// Index = (exp_field[8] << 4) | top_mantissa_bits[4]   (12 bits, 4096 entries)
// Stored value = lower 7 bits of the HiFloat8 byte (sign is OR'd by kernel)
//
// Why 12 bits suffice:
//   * HiFloat8 rounds half-away-from-zero, so no sticky bit is required.
//   * Max mantissa zone keeps 3 bits + 1 round bit = 4 mantissa bits.
//
// NaN/Inf:
//   exp == 0xFF entries are placeholders; the kernel branches on that row
//   to distinguish ±Inf (mant == 0) from NaN (mant != 0).

#ifndef HIFLOAT8_ENCODE_LUT_H
#define HIFLOAT8_ENCODE_LUT_H

#include <stdint.h>

#define HIF8_ENCODE_LUT_SIZE 4096

// Float bits → LUT-rank byte layout (lower 7 bits, no sign)
__constant__ const uint8_t HIF8_ENCODE_LUT_RANK_LO[HIF8_ENCODE_LUT_SIZE] = {{
{rank_body}
}};

// Float bits → Ascend / en-dtypes byte layout (lower 7 bits, no sign)
__constant__ const uint8_t HIF8_ENCODE_ASCEND_LO[HIF8_ENCODE_LUT_SIZE] = {{
{ascend_body}
}};

#endif  // HIFLOAT8_ENCODE_LUT_H
"""


def fmt_byte_rows(arr, per_row=16):
    parts = []
    for i in range(0, len(arr), per_row):
        chunk = arr[i:i + per_row]
        parts.append("    " + ", ".join(f"0x{v:02X}" for v in chunk) + ",")
    body = "\n".join(parts)
    return body[:-1]  # strip trailing comma


def main():
    rank_lut, ascend_lut = build_encode_tables()

    out_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "custom_ops", "hifloat8_cuda", "hifloat8_encode_lut.h",
    )
    with open(out_path, "w") as f:
        f.write(HEADER_TEMPLATE.format(
            rank_body=fmt_byte_rows(rank_lut),
            ascend_body=fmt_byte_rows(ascend_lut),
        ))
    print(f"Wrote {out_path} ({len(rank_lut)} entries × 2 tables)")


if __name__ == "__main__":
    main()
