#!/usr/bin/env python3
"""
Generate Ascend-HiFloat8 ↔ LUT-rank remap header.

The repo's CUDA kernel encodes HiFloat8 values using a "LUT-rank" byte
layout: bit 7 is sign, bits 6..0 are the value's rank in the sorted LUT.
That layout is convenient (single LUT lookup) but not what real Ascend
hardware (or the reference `en-dtypes` package) reads.

This script enumerates every uint8 in `en_dtypes.hifloat8`, derives:
  * REPO_RANK_TO_ASCEND_LO[128]  - LUT-rank index → Ascend lower-7-bit byte
                                    (rank 127 = Inf marker → 0x6F)
  * ASCEND_DECODE_LUT[128]       - Ascend lower-7-bit byte → magnitude
                                    (Ascend Inf code 0x6F → +Inf)

and emits `custom_ops/hifloat8_cuda/hifloat8_ascend_remap.h`.

Specials handled by the kernels (NOT by these tables):
  full-byte 0x80      → NaN
  full-byte 0x6F/0xEF → ±Inf
"""

from __future__ import annotations

import math
import os
import sys

import numpy as np
import en_dtypes as en


# ---------------------------------------------------------------------------
# Step 1: enumerate the repo LUT (must mirror scripts/generate_lut.py exactly)
# ---------------------------------------------------------------------------

def enumerate_repo_lut() -> list[float]:
    values = {0.0}
    for M in range(1, 8):
        values.add(2.0 ** (M - 23))
    for E in range(-15, 16):
        ae = abs(E)
        mb = 3 if ae <= 3 else (2 if ae <= 7 else 1)
        for m in range(2 ** mb):
            v = (2.0 ** E) * (1.0 + m / (2.0 ** mb))
            if v >= 1.5 * 2 ** 15:
                continue
            values.add(v)
    return sorted(values)


# ---------------------------------------------------------------------------
# Step 2: build remap tables from en-dtypes
# ---------------------------------------------------------------------------

def build_remap():
    repo_lut = enumerate_repo_lut()             # length 127
    assert len(repo_lut) == 127

    en_bytes = np.arange(256, dtype=np.uint8).view(en.hifloat8).astype(np.float64)

    # Map magnitude → Ascend lower-7-bit byte (positive side has it directly)
    mag_to_lo: dict[float, int] = {}
    inf_lo = None
    nan_full = None
    for b in range(256):
        v = float(en_bytes[b])
        if math.isnan(v):
            assert nan_full is None or nan_full == b, "multiple NaN codes"
            nan_full = b
            continue
        if math.isinf(v):
            if v > 0:
                assert inf_lo is None or inf_lo == (b & 0x7F)
                inf_lo = b & 0x7F
            continue
        mag = abs(v)
        lo = b & 0x7F
        if mag in mag_to_lo:
            assert mag_to_lo[mag] == lo, f"conflicting Ascend codes for {mag}"
        mag_to_lo[mag] = lo

    assert inf_lo is not None, "no +Inf code found in en-dtypes"
    assert nan_full == 0x80, f"unexpected NaN slot: 0x{nan_full:02X}"

    # REPO_RANK_TO_ASCEND_LO[rank] → Ascend lower-7-bit byte
    # rank in [0, 126]: ordinary finite value
    # rank == 127      : sentinel for +Inf (matches HIF8_IDX_INF in the repo LUT)
    rank_to_lo = [0] * 128
    for rank, val in enumerate(repo_lut):
        rank_to_lo[rank] = mag_to_lo[val]
    rank_to_lo[127] = inf_lo

    # ASCEND_DECODE_LUT[lo] → magnitude (for lo in [0, 0x7F])
    # The Inf slot stores +Inf so decode can be a single LUT load.
    ascend_decode = [float("nan")] * 128
    for b in range(128):
        v = float(en_bytes[b])
        if math.isnan(v):
            # 0x00 is zero, never NaN on the positive side
            ascend_decode[b] = 0.0
        elif math.isinf(v):
            ascend_decode[b] = math.inf
        else:
            ascend_decode[b] = v

    return repo_lut, rank_to_lo, ascend_decode, inf_lo


# ---------------------------------------------------------------------------
# Step 3: emit the C header
# ---------------------------------------------------------------------------

HEADER_TEMPLATE = """\
// Auto-generated by scripts/generate_ascend_remap.py
// DO NOT EDIT MANUALLY
//
// Maps the repo's "LUT-rank" HiFloat8 byte layout to/from the Ascend
// HiFloat8 byte layout used by `en_dtypes.hifloat8` and the Ascend NPU.
//
// Layout (Ascend):
//   bit 7      = sign
//   bits 6..0  = field-encoded magnitude
//   full-byte 0x80      = NaN (only NaN encoding)
//   full-byte 0x6F/0xEF = +Inf / -Inf
//   full-byte 0x00      = +0 (no -0 representation)

#ifndef HIFLOAT8_ASCEND_REMAP_H
#define HIFLOAT8_ASCEND_REMAP_H

#include <stdint.h>

// Ascend specials referenced by the kernels
#define ASCEND_NAN   0x80
#define ASCEND_PINF  {pinf:#04x}
#define ASCEND_NINF  {ninf:#04x}
#define ASCEND_ZERO  0x00

// Repo LUT-rank index → Ascend lower-7-bit byte.
// Index in [0, 126] = ordinary finite value (rank in HIF8_DECODE_LUT).
// Index 127        = sentinel matching HIF8_IDX_INF (encodes ±Inf).
__constant__ const uint8_t REPO_RANK_TO_ASCEND_LO[128] = {{
{rank_to_lo_body}
}};

// Ascend lower-7-bit byte → magnitude (positive value).
// Ascend's +Inf code (ASCEND_PINF) is stored as +Inf in the table so
// decoding is one __constant__ load + sign flip. Full-byte 0x80 must be
// recognised as NaN BEFORE indexing this table (decoded as 0 here).
__constant__ const float ASCEND_DECODE_LUT[128] = {{
{ascend_decode_body}
}};

#endif  // HIFLOAT8_ASCEND_REMAP_H
"""


def fmt_uint8_rows(arr, per_row=8):
    out = []
    for i in range(0, len(arr), per_row):
        chunk = arr[i:i + per_row]
        out.append("    " + ", ".join(f"0x{v:02X}" for v in chunk) + ",")
    body = "\n".join(out)
    return body[:-1]  # strip trailing comma off last item for cleanliness


def fmt_float_rows(arr, per_row=4):
    out = []
    for i in range(0, len(arr), per_row):
        chunk = arr[i:i + per_row]
        cells = []
        for v in chunk:
            if math.isinf(v):
                cells.append("INFINITY")
            elif math.isnan(v):
                cells.append("NAN")
            elif v == 0.0:
                cells.append("0.0f")
            else:
                cells.append(v.hex() + "f")
        out.append("    " + ", ".join(cells) + ",")
    body = "\n".join(out)
    return body[:-1]


def main():
    repo_lut, rank_to_lo, ascend_decode, inf_lo = build_remap()

    # Self-checks
    assert rank_to_lo[127] == inf_lo
    assert all(0 <= b < 0x80 for b in rank_to_lo[:127])
    assert ascend_decode[inf_lo] == math.inf
    assert ascend_decode[0] == 0.0

    # Sanity: every finite repo value must round-trip through Ascend tables
    for rank, val in enumerate(repo_lut):
        lo = rank_to_lo[rank]
        decoded = ascend_decode[lo]
        if val == 0.0:
            assert decoded == 0.0
        else:
            assert decoded == val, f"rank {rank}: stored {decoded} expected {val}"

    header = HEADER_TEMPLATE.format(
        pinf=inf_lo,
        ninf=inf_lo | 0x80,
        rank_to_lo_body=fmt_uint8_rows(rank_to_lo),
        ascend_decode_body=fmt_float_rows(ascend_decode),
    )

    out_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "custom_ops", "hifloat8_cuda", "hifloat8_ascend_remap.h",
    )
    with open(out_path, "w") as f:
        f.write(header)

    print(f"Wrote {out_path}")
    print(f"  Ascend +Inf code: 0x{inf_lo:02X}")
    print(f"  Ascend NaN code : 0x80")
    print(f"  Repo LUT size   : {len(repo_lut)} (127 expected)")


if __name__ == "__main__":
    main()
